server:
  port: 2222

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: dingup-consumer

spring:
  application:
      name: consumer1
  
  
